// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8GHhQO0-s7MVBgRYV7EI8NS8fWgDY6n4',
    appId: '1:678129175182:web:ef932333bf887d069117df',
    messagingSenderId: '678129175182',
    projectId: 'todo-81581',
    authDomain: 'todo-81581.firebaseapp.com',
    storageBucket: 'todo-81581.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0lL4aWACrrh4qhhMsp5yABTLpuQmgBzI',
    appId: '1:678129175182:android:1f9236e27a47fcdb9117df',
    messagingSenderId: '678129175182',
    projectId: 'todo-81581',
    storageBucket: 'todo-81581.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_QQlB90QrfX1ypJlpK0NJP22tyVLoz4E',
    appId: '1:678129175182:ios:6d195a7eff862c2d9117df',
    messagingSenderId: '678129175182',
    projectId: 'todo-81581',
    storageBucket: 'todo-81581.appspot.com',
    iosBundleId: 'com.example.todoBrsk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_QQlB90QrfX1ypJlpK0NJP22tyVLoz4E',
    appId: '1:678129175182:ios:6d195a7eff862c2d9117df',
    messagingSenderId: '678129175182',
    projectId: 'todo-81581',
    storageBucket: 'todo-81581.appspot.com',
    iosBundleId: 'com.example.todoBrsk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8GHhQO0-s7MVBgRYV7EI8NS8fWgDY6n4',
    appId: '1:678129175182:web:8b9b23d94333d0589117df',
    messagingSenderId: '678129175182',
    projectId: 'todo-81581',
    authDomain: 'todo-81581.firebaseapp.com',
    storageBucket: 'todo-81581.appspot.com',
  );
}
